FROM openapitools/openapi-generator-cli

ARG HOST_UID

RUN addgroup --gid $HOST_UID vscode \
  && adduser --uid $HOST_UID --gid $HOST_UID vscode

WORKDIR /app

RUN ln -s /usr/local/bin/docker-entrypoint.sh /usr/local/bin/openapi-generator-cli

USER vscode

CMD ["sleep", "infinity"]