FROM node:lts-alpine

ARG HOST_UID

RUN apk add chromium \
  && apk add git \
  && apk update \
  && apk upgrade
ENV CHROME_BIN='/usr/bin/chromium-browser'

RUN deluser --remove-home node \
  && addgroup -S vscode -g $HOST_UID \
  && adduser -S -G vscode -u $HOST_UID vscode

WORKDIR /app/angular

RUN rm -rf node_modules && npm cache clean -f && npm install -g npm@latest @angular/cli

USER vscode

CMD ["sleep", "infinity"]