FROM node:lts-alpine

RUN apk add chromium \
  && apk add git \
  && apk update \
  && apk upgrade
ENV CHROME_BIN='/usr/bin/chromium-browser'

RUN deluser --remove-home node \
  && addgroup -S vscode -g 1000 \
  && adduser -S -G vscode -u 1000 vscode

WORKDIR /app

RUN npm install -g npm@latest

RUN npm install -g @angular/cli

USER vscode

CMD ["sleep", "infinity"]