FROM mcr.microsoft.com/dotnet/sdk:8.0

ARG HOST_UID

RUN groupadd --gid $HOST_UID vscode \
    && useradd --uid $HOST_UID --gid vscode --shell /bin/bash --create-home vscode

WORKDIR /app/dotnet

USER vscode

RUN dotnet dev-certs https \
    && dotnet tool update -g dotnet-aspnet-codegenerator --version 8.0.7 \
    && dotnet tool update --global dotnet-ef --version 8.0.11 \
    && dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.4.3

ENV PATH="${PATH}:/home/vscode/.dotnet/tools"

CMD ["sleep", "infinity"]