FROM mcr.microsoft.com/dotnet/sdk:7.0

RUN groupadd --gid 1000 vscode \
    && useradd --uid 1000 --gid vscode --shell /bin/bash --create-home vscode

WORKDIR /app/dotnet

USER vscode

RUN dotnet dev-certs https \
    && dotnet tool update -g dotnet-aspnet-codegenerator --version 7.0.12 \
    && dotnet tool update --global dotnet-ef --version 7.0.20 \
    && dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.3.7

ENV PATH="${PATH}:/home/vscode/.dotnet/tools"
    
CMD ["sleep", "infinity"]