ALTER SESSION SET CONTAINER = XEPDB1;
-- DROP USER IPENSION;
CREATE USER IPENSION IDENTIFIED BY password;
ALTER USER IPENSION QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO IPENSION;
CREATE OR REPLACE DIRECTORY EXP_DIR AS '/home/oracle';
GRANT READ, WRITE ON DIRECTORY EXP_DIR TO IPENSION;
GRANT EXP_FULL_DATABASE TO IPENSION;
GRANT IMP_FULL_DATABASE TO IPENSION;
-- expdp IPENSION/password@XEPDB1 schemas=CTSPENSION directory=EXP_DIR dumpfile=CTSPENSION.dmp logfile=CTSPENSION.log
-- impdp IPENSION/password@XEPDB1 schemas=CTSPENSION directory=EXP_DIR dumpfile=CTSPENSION.dmp logfile=CTSPENSION.log remap_schema=CTSPENSION:CTSPENSION
