ALTER SESSION SET CONTAINER = XEPDB1;
-- DROP USER IPENSION;
CREATE USER IPENSION
-- IDENTIFIED BY <password>
;

CREATE TABLE "IPENSION"."P_MD_EMP_NOMINEE_DTL" 
   (	"INT_PEN_NOM_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PENSIONER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_NOM_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_EMPLOYEE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"NOMINEE_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"GENDER" CHAR(1), 
	"INT_MARITAL_STATUS_ID" NUMBER(38,0), 
	"DATE_OF_BIRTH" DATE NOT NULL ENABLE, 
	"MINOR_FLAG" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"GUARDIAN_NAME" VARCHAR2(200), 
	"IDENTIFICATION_MARK" VARCHAR2(100), 
	"SHARE_PERCENTAGE" NUMBER(5,0), 
	"BANK_AC_NO" VARCHAR2(30), 
	"IFSC_CODE" VARCHAR2(11), 
	"PRIORITY_LEVEL" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
	"MINOR_FLAG_CALCULATED_ON" DATE DEFAULT SYSDATE, 
	"BENF_TYPE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"NOMINEE_TYPE" CHAR(1) DEFAULT 'O' NOT NULL ENABLE, 
	"MOBILE_NUMBER" VARCHAR2(11), 
	"DML_STATUS_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	"INT_EMP_RELATIONSHIP_ID" NUMBER(38,0), 
	"NOM_INT_OMI_PHYSIC_CHALLENGED" NUMBER(38,0), 
	"NOM_PHYSIC_CHALLENGED_PERC_VH" NUMBER(3,0), 
	"NOM_PHYSIC_CHALLENGED_PERC_PH" NUMBER(3,0), 
	"INT_RELATION_ADDR_ID" NUMBER(38,0), 
	"HOUSE_NO_STREET_LANE" VARCHAR2(100), 
	"CITY_TOWN_VILLAGE" VARCHAR2(100), 
	"POST_OFFICE" VARCHAR2(100), 
	"POLICE_STATION" VARCHAR2(100), 
	"STATE_ID" NUMBER(2,0), 
	"INT_DISTRICT_ID" NUMBER(5,0), 
	"PIN" VARCHAR2(10), 
	"GUARDIAN_ADDR" VARCHAR2(500), 
	"RELATION_IN_OUT" VARCHAR2(1), 
	"ROLE_ID" NUMBER(6,0), 
	"MODIFIED_ROLE_ID" NUMBER(6,0), 
	"REQUEST_ID" NUMBER(15,0), 
	"ORG_NOM_ID_FOR_ALTERNATE" NUMBER(38,0), 
	"ACTIVE_FLAG" VARCHAR2(1), 
	"DECLARATION_FOR_NOMINEE" VARCHAR2(300), 
	"ESE_FLAG" VARCHAR2(1), 
	"PROCESSING_FLAG" NUMBER(1,0), 
	"EMAIL_ID" VARCHAR2(100), 
	"NOM_CONTINGENCY" VARCHAR2(500), 
	"REMARKS" VARCHAR2(500), 
	"REASON" VARCHAR2(500), 
	"CREATION_AFTER_DEATH_FLAG" VARCHAR2(1), 
	"NOM_DECEASED_FLAG" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"AGE_ON_CREATED_DATE" VARCHAR2(100), 
	"OUT_REL_DESC" VARCHAR2(500), 
	"NOMINEE_LEGAL_HIRE_FLAG" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	 CONSTRAINT "PK_P_MD_EMP_NOMINEE_DTL" PRIMARY KEY ("INT_PEN_NOM_ID") ENABLE
   )  ;

COMMENT ON COLUMN IPENSION.P_MD_EMP_NOMINEE_DTL.CREATED_TIMESTAMP IS 'nominee creation and application date -- added by ritu';
COMMENT ON COLUMN IPENSION.P_MD_EMP_NOMINEE_DTL.RELATION_IN_OUT IS '
Relation In - 0, out - 1 --added by ritu';
COMMENT ON COLUMN IPENSION.P_MD_EMP_NOMINEE_DTL.ORG_NOM_ID_FOR_ALTERNATE IS 'original nominee id for whom this person is an alternate --added by ritu';
COMMENT ON COLUMN IPENSION.P_MD_EMP_NOMINEE_DTL.PROCESSING_FLAG IS '0 initiate, 1    approved, -1 rejected';
COMMENT ON COLUMN IPENSION.P_MD_EMP_NOMINEE_DTL.REASON IS 'reason for relation - out --added by ritu';
COMMENT ON COLUMN IPENSION.P_MD_EMP_NOMINEE_DTL.CREATION_AFTER_DEATH_FLAG IS 'Nominee created after death of employee Y/N';
COMMENT ON COLUMN IPENSION.P_MD_EMP_NOMINEE_DTL.NOM_DECEASED_FLAG IS '''Y'' for alive ''N'' for dead';
COMMENT ON COLUMN IPENSION.P_MD_EMP_NOMINEE_DTL.AGE_ON_CREATED_DATE IS 'Nominee age on created date for report';
COMMENT ON COLUMN IPENSION.P_MD_EMP_NOMINEE_DTL.NOMINEE_LEGAL_HIRE_FLAG IS 'N - nominee L - Legal Hier --added by pk pandit';

CREATE TABLE "IPENSION"."P_MD_PENSIONER_ADDRESS" 
   (	"INT_PENSIONER_ADDR_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_EMPLOYEE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PENSIONER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"HOUSE_NO_STREET_LANE" VARCHAR2(100), 
	"CITY_TOWN_VILLAGE" VARCHAR2(100), 
	"POST_OFFICE" VARCHAR2(100), 
	"POLICE_STATION" VARCHAR2(100), 
	"STATE_ID" NUMBER(2,0), 
	"INT_DISTRICT_ID" NUMBER(5,0), 
	"PIN" VARCHAR2(10), 
	"WEF" DATE, 
	"ADDR_TYPE" VARCHAR2(5), 
	"SAME_AS_PERMANENT_ADDR" VARCHAR2(5) DEFAULT 'N', 
	"ACTIVE_FLAG" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CREATED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"EFFECTIVE_END_DATE" DATE, 
	"DML_STATUS_FLAG" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER(15,0), 
	"COUNTRY_ID" NUMBER(2,0), 
	"ROLE_ID" NUMBER(6,0), 
	"MODIFIED_ROLE_ID" NUMBER(6,0), 
	 CONSTRAINT "PK_P_MD_PENSIONER_ADDRESS" PRIMARY KEY ("INT_PENSIONER_ADDR_ID") ENABLE, 
	 CONSTRAINT "CHK_HR_MD_EMP_ADDRESS" CHECK (ADDR_TYPE in('PM','PR','CC')) ENABLE
   );

COMMENT ON COLUMN IPENSION.P_MD_PENSIONER_ADDRESS.ADDR_TYPE IS 'PM for Permanent, PR for present CM for communication address';
COMMENT ON COLUMN IPENSION.P_MD_PENSIONER_ADDRESS.SAME_AS_PERMANENT_ADDR IS 'N or Y';

CREATE TABLE "IPENSION"."P_MD_PEN_EMP_COPY_FORWARD_TO" 
   (	"INT_COPY_FORWARD_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PENSIONER_ID" NUMBER(38,0), 
	"SEQ_NO" NUMBER(4,0), 
	"COPY_FORWARD_TO_TEXT" VARCHAR2(500), 
	"ACTIVE_FLAG" VARCHAR2(1), 
	"DML_STATUS_FLAG" NUMBER(1,0), 
	 CONSTRAINT "PK_P_MD_PEN_COPY_FORWARD_TO" PRIMARY KEY ("INT_COPY_FORWARD_ID") ENABLE
   );
;

CREATE TABLE "IPENSION"."P_MD_PEN_EMP_WISE_FORWARD_LIST" 
   (	"INT_PEN_FORWARDING_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PENSIONER_ID" NUMBER(38,0), 
	"SL_NO" NUMBER(4,0), 
	"FORWARDING_TEXT" VARCHAR2(500), 
	"ACTIVE_FLAG" VARCHAR2(1) DEFAULT 'Y', 
	"DML_STATUS_FLAG" NUMBER(1,0), 
	 CONSTRAINT "PK_MD_PEN_EMP_WISE_FORWARDING" PRIMARY KEY ("INT_PEN_FORWARDING_ID") ENABLE
   );

COMMENT ON COLUMN IPENSION.P_MD_PEN_EMP_WISE_FORWARD_LIST.ACTIVE_FLAG IS '''Y'' / ''N'' Flag';

CREATE TABLE "IPENSION"."P_MD_PEN_PREP_ATTACHMENT" 
   (	"INT_PEN_PREP_ATTACHEMENT" NUMBER(38,0) NOT NULL ENABLE, 
	"SERVICE_BOOK_EXIT_MNGMNT_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"DOCUMENT_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"CONTENT_ID" VARCHAR2(38) NOT NULL ENABLE, 
	"INT_EMPLOYEE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER(15,0), 
	"REQUEST_TYPE" VARCHAR2(15), 
	"FILE_NAME" VARCHAR2(100), 
	"FILE_TYPE" VARCHAR2(20), 
	"ACTIVE_FLAG" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"DML_STATUS_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_ROLE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0, 
	"MODIFIED_ROLE_ID" NUMBER(6,0), 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp, 
	"INT_OMI_UPD_DOC_TYPE" NUMBER(38,0), 
	 CONSTRAINT "PK_P_MD_PEN_PREP_ATTACHEMENT" PRIMARY KEY ("INT_PEN_PREP_ATTACHEMENT") ENABLE, 
	 CONSTRAINT "UK_P_MD_PEN_PREP_ATTACHEMENT1" UNIQUE ("DOCUMENT_ID") ENABLE, 
	 CONSTRAINT "UK_P_MD_PEN_PREP_ATTACHEMENT2" UNIQUE ("CONTENT_ID") ENABLE
   );

COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_ATTACHMENT.SERVICE_BOOK_EXIT_MNGMNT_FLAG IS 'For Service book : ''S'' for Exit Management ''E''';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_ATTACHMENT.INT_OMI_UPD_DOC_TYPE IS 'document type from other master master type: ''AFT''';

CREATE TABLE "IPENSION"."P_MD_PEN_PREP_CALCULATED_AMT" 
   (	"INT_PREP_CALCULATED_AMT_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PENSIONER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PEN_PREP_CALC_HEADER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ITERATION_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"BENF_TYPE_ID" NUMBER(38,0), 
	"PEN_TYPE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PEN_PREP_CALC_HDR_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PEN_RULE_DTLS_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"AMOUNT_SYSTEM" NUMBER(20,0), 
	"AMOUNT_APPLICABLE_FOR_CALC" NUMBER(20,0), 
	"ACTIVE_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"DML_STATUS_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"CREATED_ROLE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"MODIFIED_ROLE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"FORMULA_WITH_VALUE" VARCHAR2(500), 
	"WORKFLOW_STATUS_FLAG" VARCHAR2(2) NOT NULL ENABLE, 
	 CONSTRAINT "PK_PEN_PREP_CALCULATED_AMT" PRIMARY KEY ("INT_PREP_CALCULATED_AMT_ID") ENABLE
   );
;

CREATE TABLE "IPENSION"."P_MD_PEN_PREP_CALCULATION_HDR" 
   (	"INT_PEN_PREP_CALC_HDR_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PENSIONER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PEN_PREP_CALC_HEADER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ITERATION_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"INT_PEN_RULE_NAME_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"NET_QUALIFYING_SERVICE_YR" NUMBER(10,0), 
	"NET_QUALIFYING_SERVICE_MON" NUMBER(10,0), 
	"NET_QUALIFYING_SERVICE_DAYS" NUMBER(10,0), 
	"LAST_PAY" NUMBER(10,0), 
	"LAST_BASIC" NUMBER(10,0), 
	"LAST_GRADE_PAY" NUMBER(10,0), 
	"LAST_DA" NUMBER(10,0), 
	"DATE_OF_BIRTH" DATE NOT NULL ENABLE, 
	"DATE_OF_RETIREMENT" DATE NOT NULL ENABLE, 
	"AGE_AT_NEXT_BIRTHDAY" NUMBER(10,0) NOT NULL ENABLE, 
	"DML_STATUS_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"CREATED_ROLE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"MODIFIED_ROLE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"WORKFLOW_STATUS_FLAG" VARCHAR2(2) NOT NULL ENABLE, 
	"LAST_MA" NUMBER(10,0), 
	 CONSTRAINT "PK_PEN_PREP_CALCULATION_HDR" PRIMARY KEY ("INT_PEN_PREP_CALC_HDR_ID") ENABLE
   );
;

CREATE TABLE "IPENSION"."P_MD_PEN_PREP_EMOLUMENT_DTLS" 
   (	"INT_PEN_PREP_EML_DTLS_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PENSIONER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PEN_PREP_CALC_HEADER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ITERATION_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"INT_COMPONENT_ID" NUMBER(38,0), 
	"COMPONENT_NAME" VARCHAR2(300), 
	"INT_COMPONENT_ID_DEPUTATION" NUMBER(38,0), 
	"WEF_DATE" DATE, 
	"AMOUNT_SYSTEM" NUMBER(20,0), 
	"AMOUNT_APPLICABLE_FOR_CALC" NUMBER(20,0), 
	"HRMS_DEPUTATION_FLAG" VARCHAR2(2), 
	"ACTIVE_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"DML_STATUS_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"CREATED_ROLE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"MODIFIED_ROLE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"WORKFLOW_STATUS_FLAG" VARCHAR2(2) NOT NULL ENABLE, 
	"CALC_INCLUDE_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	 CONSTRAINT "PK_P_MD_PEN_PREP_EMOL_DTLS" PRIMARY KEY ("INT_PEN_PREP_EML_DTLS_ID") ENABLE
   );
;

CREATE TABLE "IPENSION"."P_MD_PEN_PREP_OTH_OUTSTANDING" 
   (	"INT_PEN_OTH_OUTSTANDING_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PENSIONER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PEN_PREP_CALC_HEADER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ITERATION_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"OUTSTANDING_TYPE" VARCHAR2(2) NOT NULL ENABLE, 
	"COMP_DESCRIPTION" VARCHAR2(200), 
	"INT_OVERDRAWL_DETAILS_ID" NUMBER(38,0), 
	"INT_COMPONENT_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"AMOUNT" NUMBER(10,2) NOT NULL ENABLE, 
	"FROM_DATE" DATE, 
	"RECOVERY_FLAG" VARCHAR2(1), 
	"HOA_ID" NUMBER(6,0), 
	"DEMAND_NO" VARCHAR2(2), 
	"MAJOR_HEAD" VARCHAR2(4), 
	"SUBMAJOR_HEAD" VARCHAR2(2), 
	"MINOR_HEAD" VARCHAR2(3), 
	"PLAN_STATUS" VARCHAR2(2), 
	"SCHEME_HEAD" VARCHAR2(3), 
	"DETAIL_HEAD" VARCHAR2(2) NOT NULL ENABLE, 
	"SUBDETAIL_HEAD" VARCHAR2(2) NOT NULL ENABLE, 
	"CHARGED_VOTED" VARCHAR2(1), 
	"MODIFIABLE_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"ACTIVE_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"DML_STATUS_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"CREATED_ROLE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"MODIFIED_ROLE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"WORKFLOW_STATUS_FLAG" VARCHAR2(2) NOT NULL ENABLE, 
	"REMARKS" VARCHAR2(100), 
	"OVRDRAWAL_REASON" VARCHAR2(500), 
	"RECOVERED_AMOUNT" NUMBER(8,0), 
	"DIFFERENCE_AMOUNT" NUMBER(8,0), 
	 CONSTRAINT "PK_P_MD_PEN_PREP_OTH_OUTSTAND" PRIMARY KEY ("INT_PEN_OTH_OUTSTANDING_ID") ENABLE
   );

COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_OTH_OUTSTANDING.OUTSTANDING_TYPE IS '''PA''--- Pay Allowance type overdrawl out standing, ''OTH'' other outstanding';

CREATE TABLE "IPENSION"."P_MD_PEN_PREP_OUTSTANDING_LOAN" 
   (	"INT_PEN_OUTSTANDING_LOAN_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PENSIONER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PEN_PREP_CALC_HEADER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ITERATION_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"INT_LOAN_ADVANCE_TYPE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_EMP_LOAN_ADVANCE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_COMPONENT_ID_PRIN" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_COMPONENT_ID_INT" NUMBER(38,0), 
	"OUTSTANDING_AS_ON_DATE" DATE, 
	"SANCTION_DATE" DATE, 
	"OUT_STANDING_PRIN_AMT" NUMBER(10,2), 
	"OUT_STANDING_INT_AMT" NUMBER(10,2), 
	"REMARKS" VARCHAR2(100), 
	"MODIFIABLE_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"ACTIVE_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"DML_STATUS_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"CREATED_ROLE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"MODIFIED_ROLE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"WORKFLOW_STATUS_FLAG" VARCHAR2(2) NOT NULL ENABLE, 
	 CONSTRAINT "PK_P_MD_PEN_PREP_OS_LOAN" PRIMARY KEY ("INT_PEN_OUTSTANDING_LOAN_ID") ENABLE
   );
;

CREATE TABLE "IPENSION"."P_MD_PEN_PREP_OUTSTND_LOAN_DTL" 
   (	"INT_PEN_OUTSTND_LOAN_DTL_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PEN_OUTSTANDING_LOAN_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PENSIONER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PEN_PREP_CALC_HEADER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ITERATION_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"INT_EMP_RECOVERY_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_COMP_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"RECOVERY_AMOUNT" NUMBER(7,0) NOT NULL ENABLE, 
	"WEF" DATE NOT NULL ENABLE, 
	"EFFECTIVE_END_DATE" DATE NOT NULL ENABLE, 
	"INT_EMP_LOAN_ADVANCE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PAID_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"PAID_DATE" DATE, 
	"PAID_AMOUNT" NUMBER(10,2), 
	"LEGACY_FLAG" VARCHAR2(1), 
	"INT_EMP_LOAN_ADV_FC_ID" NUMBER(38,0), 
	"REMARKS" VARCHAR2(100), 
	"MODIFIABLE_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"ACTIVE_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"DML_STATUS_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"CREATED_ROLE_ID" NUMBER(6,0), 
	"MODIFIED_ROLE_ID" NUMBER(6,0), 
	 CONSTRAINT "PK_P_MD_PEN_OUTS_LOAN_DTL" PRIMARY KEY ("INT_PEN_OUTSTND_LOAN_DTL_ID") ENABLE
   );

CREATE TABLE "IPENSION"."P_MD_PEN_PREP_PAY_DTLS" 
   (	"INT_PEN_PREP_PAY_DTLS_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PENSIONER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PEN_PREP_CALC_HEADER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ITERATION_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"INT_PAY_BAND_ID" NUMBER(38,0), 
	"INT_PAY_SCALE_ID" NUMBER(38,0), 
	"INT_REV_PAY_ALLOWANCE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PAY_SCALE_BAND_NAME" VARCHAR2(300) NOT NULL ENABLE, 
	"ROPA_NAME" VARCHAR2(300) NOT NULL ENABLE, 
	"ACTIVE_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"DML_STATUS_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"CREATED_ROLE_ID" NUMBER(6,0), 
	"MODIFIED_ROLE_ID" NUMBER(6,0), 
	"WORKFLOW_STATUS_FLAG" VARCHAR2(2) NOT NULL ENABLE, 
	"INT_PAY_BILL_GROUP_ID" NUMBER(38,0), 
	"NEXT_INCRIMENT_DATE" DATE, 
	"NEXT_INCRISE_BASIC_AMT" NUMBER(8,0), 
	"NEXT_INCRISE_SPECIAL_PAY" NUMBER(8,0), 
	"TOT_SAL_DRAWN" NUMBER(10,0), 
	"TOT_SAL_DRAWN_DATE" DATE, 
	"NEXT_INCRISE_NPA_AMT" NUMBER(8,0), 
	"NEXT_INCRISE_SPCL_PAY_MODIFIED" NUMBER(8,0), 
	"IMMEDIATE_RELIEF_PAID_FLAG" VARCHAR2(1), 
	"IMMEDIATE_RELIEF_PAID_AMT" NUMBER(10,0), 
	"IMMEDIATE_RELIEF_PAID_REMARKS" VARCHAR2(500), 
	 CONSTRAINT "PK_P_MD_PEN_PREP_PAY_DTLS" PRIMARY KEY ("INT_PEN_PREP_PAY_DTLS_ID") ENABLE
   );
;

CREATE TABLE "IPENSION"."P_MD_PEN_PREP_PROV_PENSION_DTL" 
   (	"INT_PEN_PROV_PENSION_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PENSIONER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PENSION_START_DATE" DATE NOT NULL ENABLE, 
	"PENSION_END_DATE" DATE NOT NULL ENABLE, 
	"MEMO_NO" VARCHAR2(100), 
	"MEMO_DATE" DATE, 
	"UO_NO" VARCHAR2(100), 
	"UO_DATE" DATE, 
	"ACTIVE_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"DML_STATUS_FLAG" NUMBER(1,0) NOT NULL ENABLE, 
	"PENSION_HOA_MAP_ID" NUMBER(38,0), 
	"GRATUITY_HOA_MAP_ID" NUMBER(38,0), 
	"PENSION_HOA_DESC" VARCHAR2(200), 
	"GRATUITY_HOA_DESC" VARCHAR2(200), 
	"REMARKS" VARCHAR2(1000), 
	"REQUEST_ID" NUMBER(38,0), 
	"CREATED_USER_ID" NUMBER(8,0) DEFAULT 99999 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 99999 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"PENSION_RATE_PER_MONTH_USER" NUMBER(6,0), 
	"TOTAL_PENSION_PERIOD_USER" VARCHAR2(100), 
	 CONSTRAINT "PK_PEN_PREP_PROV_PENSION_DTL" PRIMARY KEY ("INT_PEN_PROV_PENSION_ID") ENABLE
   );

COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_PROV_PENSION_DTL.PENSION_RATE_PER_MONTH_USER IS 'as per CR 181305';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_PROV_PENSION_DTL.TOTAL_PENSION_PERIOD_USER IS 'as per CR 181305';

CREATE TABLE "IPENSION"."P_MD_PEN_PREP_SERVICE_DTLS" 
   (	"INT_PEN_SERVICE_DTLS_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PENSIONER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_SERVICE_TYPE_ID" NUMBER(38,0), 
	"INT_PEN_PREP_CALC_HEADER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"SOURCE_ORG_ADD_SERVICE_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"FROM_DATE" DATE NOT NULL ENABLE, 
	"TO_DATE" DATE NOT NULL ENABLE, 
	"YEAR_IN_NUM" NUMBER(10,0) NOT NULL ENABLE, 
	"MONTH_IN_NUM" NUMBER(10,0) NOT NULL ENABLE, 
	"DAYS_IN_NUM" NUMBER(10,0) NOT NULL ENABLE, 
	"REMARKS" VARCHAR2(100), 
	"MODIFIABLE_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"PERIOD_TYPE" VARCHAR2(6) NOT NULL ENABLE, 
	"QUAL_NON_QUAL_WEIGHTAGE_TYPE" VARCHAR2(2) NOT NULL ENABLE, 
	"ACTIVE_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"DML_STATUS_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"CREATED_ROLE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"MODIFIED_ROLE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"ITERATION_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"INT_EMP_WORKING_DTLS_ID" NUMBER(38,0), 
	"INT_LEAVE_TYPE_ID" NUMBER(38,0), 
	"BUSINESS_PK_TYPE" VARCHAR2(5), 
	"INT_LEAVE_ID" NUMBER(38,0), 
	"INT_OTHER_SERVICE_TYPE_ID" NUMBER(38,0), 
	"INT_EMP_WORKING_DTLS_ID_DEPU" NUMBER(38,0), 
	"WORKFLOW_STATUS_FLAG" VARCHAR2(2) NOT NULL ENABLE, 
	"CONTRIBUTION_RECEIVED_FLAG" VARCHAR2(1), 
	"PENSION_RECEIVED" NUMBER(8,0), 
	"GRATUITY_RECEIVED" NUMBER(8,0), 
	"CONTRIBUTION_RECEIVED_SOURCE" VARCHAR2(500), 
	"GOVT_NAME" VARCHAR2(500), 
	"FAMILY_PENSION_FLAG" VARCHAR2(1), 
	"GO_NO" VARCHAR2(200), 
	"GO_DATE" DATE, 
	"AMT_OF_CONTRIBUTION" NUMBER(8,0), 
	 CONSTRAINT "PK_P_MD_PEN_PREP_SERVICE_DTLS" PRIMARY KEY ("INT_PEN_SERVICE_DTLS_ID") ENABLE, 
	 CONSTRAINT "CHK_P_MD_PEN_PREP_SERVICE_DTLS" CHECK (QUAL_NON_QUAL_WEIGHTAGE_TYPE in('Q','N','W')) ENABLE, 
	 CONSTRAINT "CHK_P_MD_PEN_PREP_SER_DTLS1" CHECK (PERIOD_TYPE in ('SHRMS','SNHRMS','SADD','SDEPH','SDEPNH','SNQHL','SNQNHL','SNQHS','SNQNHS','SNQO','WSADM')) ENABLE
   );

COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_SERVICE_DTLS.PERIOD_TYPE IS 'SHRMS-  Service HRMS,                 SNHRMS- Service Non HRMS,
SADD-   Additional Service,
SDEPH-  herms deputation,             SDEPNH- deputation non hrms,
SNQHL-  non qualifying hrms leave,    SNQNHL-non qualifying non hrms leave,
SNQHS-  non qualifying hrms suspence, SNQNHS-non qualifying non hrms suspence,
SNQO-   non qualifying others,        WSADM --- Weightage  ';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_SERVICE_DTLS.INT_EMP_WORKING_DTLS_ID IS 'Not required from fron end';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_SERVICE_DTLS.INT_LEAVE_TYPE_ID IS 'Not required from fron end';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_SERVICE_DTLS.BUSINESS_PK_TYPE IS 'Not required from fron end';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_SERVICE_DTLS.INT_LEAVE_ID IS 'Not required from fron end';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_SERVICE_DTLS.INT_OTHER_SERVICE_TYPE_ID IS 'will come from hr_mm_gen_other_master p WHERE p.master_abbr = ''OST''';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_SERVICE_DTLS.INT_EMP_WORKING_DTLS_ID_DEPU IS 'Not required from fron end For Deputation';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_SERVICE_DTLS.CONTRIBUTION_RECEIVED_FLAG IS '22c Any Contribution Received Y/N flag';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_SERVICE_DTLS.PENSION_RECEIVED IS '22d';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_SERVICE_DTLS.GRATUITY_RECEIVED IS '22d';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_SERVICE_DTLS.CONTRIBUTION_RECEIVED_SOURCE IS '22f';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_SERVICE_DTLS.GOVT_NAME IS 'Government under which the service';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_SERVICE_DTLS.FAMILY_PENSION_FLAG IS '22e Y/N flag';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_SERVICE_DTLS.GO_NO IS 'Added for Block ''B'' & ''C'' see CR No 181316 for Details';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_SERVICE_DTLS.GO_DATE IS 'Added for Block ''B'' & ''C'' see CR No 181316 for Details';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_SERVICE_DTLS.AMT_OF_CONTRIBUTION IS 'Added for Block ''B'' & ''C'' see CR No 181316 for Details';

CREATE TABLE "IPENSION"."P_MD_PEN_PREP_TYPE" 
   (	"CATEGORY_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PEN_TYPE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"TYPE_DESC" VARCHAR2(400) NOT NULL ENABLE, 
	"TYPE_ABBR" CHAR(1) NOT NULL ENABLE, 
	"ACTIVE_FLAG" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	"PEN_TYPE_ABBR" VARCHAR2(3), 
	"PENSION_TYPE_FLAG" VARCHAR2(1), 
	"PENSION_CALC_TYPE" VARCHAR2(2), 
	 CONSTRAINT "PK_P_MD_PEN_PREP_TYPE" PRIMARY KEY ("PEN_TYPE_ID") ENABLE, 
	 CHECK (active_flag IN ('Y','N')) ENABLE, 
	 CONSTRAINT "UK_P_MD_PEN_PREP_TYPE1" UNIQUE ("PEN_TYPE_ABBR", "PENSION_TYPE_FLAG") ENABLE
   );

COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_TYPE.CATEGORY_ID IS 'Reference column from P_MM_PEN_PREP_CATEGORY..';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_TYPE.PEN_TYPE_ID IS 'Unique pension ID type.';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_TYPE.TYPE_ABBR IS '''F'' = Family';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_TYPE.PEN_TYPE_ABBR IS 'added kalyan';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_TYPE.PENSION_TYPE_FLAG IS '''P'' for Provisional & ''F'' for Final Pension';
COMMENT ON COLUMN IPENSION.P_MD_PEN_PREP_TYPE.PENSION_CALC_TYPE IS 'Types are commomn Superannuation & ''Death'' ''SP'' & ''DP''';

CREATE TABLE "IPENSION"."P_MM_EXIT_FORWARDING_LIST" 
   (	"INT_FRWDING_LIST_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PENSIONER_ID" NUMBER(38,0), 
	"REPORT_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"REPORT_ABBR" VARCHAR2(5), 
	"ACTIVE_FLAG" VARCHAR2(5) NOT NULL ENABLE, 
	"IN_USER_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"PEN_TYPE_ID" NUMBER(38,0), 
	"PEN_TYPE_ABBR" VARCHAR2(3), 
	"MANDATORY_FLAG" VARCHAR2(5) NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	"ODR_SL_NO" NUMBER(4,0), 
	 CONSTRAINT "PK_FORWARDING_LIST" PRIMARY KEY ("INT_FRWDING_LIST_ID") ENABLE, 
	 CONSTRAINT "CHK_FORWARDING_LIST1" CHECK (ACTIVE_FLAG IN ('Y','N')) ENABLE, 
	 CONSTRAINT "CHK_FORWARDING_LIST2" CHECK (MANDATORY_FLAG IN ('Y','O','N')) ENABLE
   );

COMMENT ON TABLE IPENSION.P_MM_EXIT_FORWARDING_LIST IS 'Details required for generating forwarding letter report';
COMMENT ON COLUMN IPENSION.P_MM_EXIT_FORWARDING_LIST.INT_FRWDING_LIST_ID IS 'primary key of this table';
COMMENT ON COLUMN IPENSION.P_MM_EXIT_FORWARDING_LIST.INT_PENSIONER_ID IS 'foreign key from pension master table';
COMMENT ON COLUMN IPENSION.P_MM_EXIT_FORWARDING_LIST.REPORT_NAME IS 'name of the reports whose name needs to be displayed in the forwardign letter report';
COMMENT ON COLUMN IPENSION.P_MM_EXIT_FORWARDING_LIST.ACTIVE_FLAG IS 'value - Y for active and N for inactive';
COMMENT ON COLUMN IPENSION.P_MM_EXIT_FORWARDING_LIST.IN_USER_ID IS 'user id of the person who will be generating the report';
COMMENT ON COLUMN IPENSION.P_MM_EXIT_FORWARDING_LIST.PEN_TYPE_ID IS 'foreign key from pension type table';
COMMENT ON COLUMN IPENSION.P_MM_EXIT_FORWARDING_LIST.PEN_TYPE_ABBR IS 'abbr for pension type';
COMMENT ON COLUMN IPENSION.P_MM_EXIT_FORWARDING_LIST.MANDATORY_FLAG IS 'value - Y (when mandatory for all benefit types), O (when mandatory based on a certain benefit type), N - (when not mandatory)';
COMMENT ON COLUMN IPENSION.P_MM_EXIT_FORWARDING_LIST.CREATED_TIMESTAMP IS 'time when this record was craeted.';
COMMENT ON COLUMN IPENSION.P_MM_EXIT_FORWARDING_LIST.ODR_SL_NO IS 'used for showing the list in particular order';

CREATE TABLE "IPENSION"."P_MM_PEN_BENF_TYPE_REL_MAP" 
   (	"INT_BENF_TYPE_REL_MAP_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"BENF_TYPE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_OTHER_MASTER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_BENF_TYPE_REL_MAP" PRIMARY KEY ("INT_BENF_TYPE_REL_MAP_ID") ENABLE
   );

COMMENT ON COLUMN IPENSION.P_MM_PEN_BENF_TYPE_REL_MAP.BENF_TYPE_ID IS '5=Family Pension,4=Death Gratuity';
COMMENT ON COLUMN IPENSION.P_MM_PEN_BENF_TYPE_REL_MAP.INT_OTHER_MASTER_ID IS 'master_type  = ''RL''';

CREATE TABLE "IPENSION"."P_MM_PEN_COMMUTATION_RATE" 
   (	"INT_PEN_COMMUTATION_RATE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"AGE_ON_NEXT_BIRTHDAY" NUMBER(3,0), 
	"COMMUTATION_RATE" NUMBER(4,3), 
	 CONSTRAINT "PK_P_MM_PEN_COMMUTATION_RATE" PRIMARY KEY ("INT_PEN_COMMUTATION_RATE_ID") ENABLE
   );
;

CREATE TABLE "IPENSION"."P_MM_PEN_HOA_MAP" 
   (	"INT_HOA_MAP_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"FULL_HOA" VARCHAR2(200), 
	"HOA_NAME" VARCHAR2(200), 
	"HOA_TYPE_ABBR" VARCHAR2(50), 
	"ACTIVE_FLAG" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"CREATED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_P_MM_PEN_HOA_MAP" PRIMARY KEY ("INT_HOA_MAP_ID") ENABLE
   );
;

CREATE TABLE "IPENSION"."P_MM_PEN_PREP_ATTACHEMENT" 
   (	"INT_PEN_PREP_ATTACHEMENT" NUMBER(38,0) NOT NULL ENABLE, 
	"ATTCHEMENT_DESC" VARCHAR2(300) NOT NULL ENABLE, 
	"OPTIONAL_MANDATORY_FLAG" VARCHAR2(3) NOT NULL ENABLE, 
	"ACTIVE_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"DML_STATUS_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT SYStimestamp NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT SYStimestamp NOT NULL ENABLE, 
	"ROLE_ID" NUMBER(6,0), 
	"MODIFIED_ROLE_ID" NUMBER(6,0), 
	"REQUEST_TYPE" VARCHAR2(15) NOT NULL ENABLE, 
	 CONSTRAINT "PK_P_MM_PEN_PREP_ATTACH" PRIMARY KEY ("INT_PEN_PREP_ATTACHEMENT") ENABLE, 
	 CONSTRAINT "UK_P_MM_PEN_PREP_ATTACH1" UNIQUE ("ATTCHEMENT_DESC", "REQUEST_TYPE") ENABLE, 
	 CONSTRAINT "UK_P_MM_PEN_PREP_ATTACH2" UNIQUE ("REQUEST_TYPE", "INT_PEN_PREP_ATTACHEMENT") ENABLE, 
	 CONSTRAINT "CHK_P_MM_PEN_PREP_ATTACHEMENT" CHECK (OPTIONAL_MANDATORY_FLAG in ('O','M')) ENABLE
   );
;

CREATE TABLE "IPENSION"."P_MM_PEN_PREP_CALC_HEADER" 
   (	"INT_PEN_PREP_CALC_HEADER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PENSIONER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ITERATION_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"ACTIVE_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"DATE_OF_COMMENCE_PEN_SERVICE" DATE, 
	"DATE_OF_COMMENCE_PEN" DATE, 
	"WORK_CHARGE_EMPLOYEE" VARCHAR2(1), 
	"DML_STATUS_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"CREATED_ROLE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"MODIFIED_ROLE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"WORKFLOW_STATUS_FLAG" VARCHAR2(2) NOT NULL ENABLE, 
	"PENSION_PAY_ORDER_NO" VARCHAR2(50), 
	"PENSION_PAY_ORDER_DATE" DATE, 
	"COMMUTATION_SANCTIONED_FLAG" VARCHAR2(1), 
	"IMMEDIATE_RELIEF_FLAG" VARCHAR2(1), 
	"PENSION_HOA" NUMBER(8,0), 
	"GRATUITY_HOA" NUMBER(8,0), 
	"SATISFIED_FLAG" VARCHAR2(1), 
	"REMARKS" VARCHAR2(500), 
	"PENSION_AGREED_PER_AMT_FLAG" VARCHAR2(1), 
	"PENSION_AGREED_PER_AMT_VALUE" NUMBER(10,0), 
	"PENSION_AGREED_AMT" NUMBER(10,0), 
	"PENSION_AGREED_DIFF_AMT" NUMBER(10,0), 
	"PENSION_TOTAL_AMOUNT" NUMBER(8,0), 
	"GRATUITY_TOTAL_AMOUNT" NUMBER(8,0), 
	"GRATUITY_AGREED_PER_AMT_FLAG" VARCHAR2(1), 
	"GRATUITY_AGREED_PER_AMT_VALUE" NUMBER(8,0), 
	"GRATUITY_AGREED_AMT" NUMBER(8,0), 
	"GRATUITY_AGREED_DIFF_AMT" NUMBER(8,0), 
	"REDUCED_PENSION" NUMBER(8,0), 
	"MEMO_NO" VARCHAR2(200), 
	"MEMO_DATE" DATE, 
	"LAST_PAY" NUMBER(10,0), 
	"LAST_BASIC" NUMBER(10,0), 
	"LAST_GRADE_PAY" NUMBER(10,0), 
	"LAST_DA" NUMBER(10,0), 
	"LAST_PAY_BILL_GROUP_ID" NUMBER(38,0), 
	"LAST_PAY_VOUCHER_DATE" DATE, 
	"LAST_PAYB_ID" NUMBER(38,0), 
	"LAST_PAY_SCALE_ID" NUMBER(38,0), 
	"PAY_BAND_SCALE_DESC" VARCHAR2(500), 
	"LAST_ROPA_ID" NUMBER(38,0), 
	"ENHANCED_FAMILY_PENSION_UPTO" DATE, 
	"ENHANCED_FAMILY_PENSION_AMT" NUMBER(8,0), 
	"FAMILY_PENSION_AMT" NUMBER(8,0), 
	"PENSION_CALCULATED" NUMBER(8,0), 
	"GRATUITY_CALCULATED" NUMBER(8,0), 
	"CVP_CALCULATED" NUMBER(8,0), 
	"NET_EFFECTIVE_SRV_PERIOD" NUMBER(5,2), 
	"PENSION_HOA_DESC" VARCHAR2(200), 
	"GRATUITY_HOA_DESC" VARCHAR2(200), 
	"LAST_HRA" NUMBER(10,0), 
	"LAST_MA" NUMBER(10,0), 
	"PENSION_HOA_MAP_ID" NUMBER(38,0), 
	"GRATUITY_HOA_MAP_ID" NUMBER(38,0), 
	"DEATH_GRATUITY_AMOUNT" NUMBER(8,0), 
	"IMMEDIATE_RELIEF_AMOUNT" NUMBER(10,0), 
	"COURT_CASE_MEMO_NO" VARCHAR2(200), 
	"COURT_CASE_MEMO_DATE" DATE, 
	"NO_DEMAND_MEMO_NO" VARCHAR2(200), 
	"NO_DEMAND_MEMO_DATE" DATE, 
	"EPF_ENHANCED_UPTO" DATE, 
	"PROV_MONTHLY_PEN_AMT_SYS" NUMBER(8,0), 
	"PROV_MONTHLY_PEN_AMT_USER" NUMBER(8,0), 
	"PROV_DEATH_GRATUITY_AMT_SYS" NUMBER(8,0), 
	"PROV_DEATH_GRATUITY_AMT_USER" NUMBER(8,0), 
	"PROV_FAMILY_PEN_AMT_SYS" NUMBER(8,0), 
	"PROV_FAMILY_PEN_AMT_USER" NUMBER(8,0), 
	"PROV_GRATUITY_AMT_SYS" NUMBER(8,0), 
	"PROV_GRATUITY_AMT_USER" NUMBER(8,0), 
	"PROV_GRATUITY_FORMULA_N_VALUE" VARCHAR2(500), 
	"INT_PEN_PROV_RULE_DTLS_ID" NUMBER(38,0), 
	"INT_PEN_PROV_GRAT_RULE_DTLS_ID" NUMBER(38,0), 
	"PROV_FORMULA_WITH_VALUE" VARCHAR2(500), 
	"NET_QUALIFING_SERVICE_YEAR" NUMBER(2,0), 
	"NET_QUALIFING_SERVICE_MONTH" NUMBER(2,0), 
	"NET_QUALIFING_SERVICE_DAYS" NUMBER(2,0), 
	"PROV_PEN_INCLUDE_EXCLUDE_FLAG" VARCHAR2(1), 
	"PROV_GRAT_INCLUDE_EXCLUDE_FLAG" VARCHAR2(1), 
	"LAST_DA_RATE" NUMBER(20,2), 
	"LAST_NPA" NUMBER(10,0), 
	 CONSTRAINT "PK_P_MM_PEN_PREP_CALC_HEADER" PRIMARY KEY ("INT_PEN_PREP_CALC_HEADER_ID") ENABLE, 
	 CONSTRAINT "UK_P_MM_PEN_PREP_CALC_HEADER1" UNIQUE ("INT_PENSIONER_ID", "ITERATION_NO") ENABLE, 
	 CONSTRAINT "UK_P_MM_PEN_PREP_CALC_HEADER2" UNIQUE ("INT_PEN_PREP_CALC_HEADER_ID", "ITERATION_NO") ENABLE
   );

COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_CALC_HEADER.COMMUTATION_SANCTIONED_FLAG IS '''Y''/''N'' flag';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_CALC_HEADER.IMMEDIATE_RELIEF_FLAG IS '''Y''/''N'' flag';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_CALC_HEADER.SATISFIED_FLAG IS '''Y''/''N'' flag';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_CALC_HEADER.PENSION_AGREED_PER_AMT_FLAG IS '''P'' for percentage ''A'' for Amount';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_CALC_HEADER.GRATUITY_AGREED_PER_AMT_FLAG IS '''P'' for percentage ''A'' for Amount';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_CALC_HEADER.MEMO_NO IS 'memo no  to be given before approving calculation';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_CALC_HEADER.MEMO_DATE IS 'memo date to be given before approving calculation';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_CALC_HEADER.PENSION_CALCULATED IS 'data will be storred for Supperannuation system_calc_Basic Pension_amt or User_updated_Basic Pension_amt';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_CALC_HEADER.IMMEDIATE_RELIEF_AMOUNT IS 'If Immidiate Relief Flag is Yes then Immidiate Relief Amount to be filled';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_CALC_HEADER.INT_PEN_PROV_RULE_DTLS_ID IS 'Rule used for calculation of normal provisional pension';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_CALC_HEADER.INT_PEN_PROV_GRAT_RULE_DTLS_ID IS 'Rule used for calculation of normal provisional Gratuity';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_CALC_HEADER.PROV_PEN_INCLUDE_EXCLUDE_FLAG IS '''Y'' = include ''N'' = Exclude';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_CALC_HEADER.PROV_GRAT_INCLUDE_EXCLUDE_FLAG IS '''Y'' = include ''N'' = Exclude';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_CALC_HEADER.LAST_DA_RATE IS 'Percentage at which DA calculated';

CREATE TABLE "IPENSION"."P_MM_PEN_PREP_DECLARATION" 
   (	"INT_PREP_DECLARATION_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"RETIREMENT_TYPE" VARCHAR2(2) NOT NULL ENABLE, 
	"DECLARATIOIN_TEXT" VARCHAR2(100) NOT NULL ENABLE, 
	"ACTIVE_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"DML_STATUS_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_BY_USER" NUMBER(6,0) NOT NULL ENABLE, 
	"MODIFIED_BY_USER" NUMBER(6,0), 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6), 
	"PEN_TYPE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_P_MM_PEN_PREP_DECLARATION" PRIMARY KEY ("INT_PREP_DECLARATION_ID") ENABLE
   );

COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_DECLARATION.RETIREMENT_TYPE IS 'P for pension, C for CVP application etc';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_DECLARATION.PEN_TYPE_ID IS 'Unique pension ID type.';

CREATE TABLE "IPENSION"."P_MM_PEN_PREP_PAY_RECO_TYPE" 
   (	"PAY_RECO_TYPE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PAY_RECO_DESC" VARCHAR2(200) NOT NULL ENABLE, 
	"PAY_RECO_ABBR" CHAR(2) NOT NULL ENABLE, 
	"COMPONENT_TYPE" CHAR(1) NOT NULL ENABLE, 
	"PAY_RECO_FLAG" CHAR(1) NOT NULL ENABLE, 
	"RECOVERY_FROM" CHAR(1) NOT NULL ENABLE, 
	"TRES_BREAKUP_CLASS_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"TRES_BREAKUP_CLASS_TYPE" CHAR(1) NOT NULL ENABLE, 
	"PAYMENT_ORDER_FLAG" CHAR(1) DEFAULT 'P' NOT NULL ENABLE, 
	"HOA_ID" VARCHAR2(6), 
	"ACTIVE_FLAG" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_P_MM_PEN_PREP_PAY_RECO_TYPE" PRIMARY KEY ("PAY_RECO_TYPE_ID") ENABLE, 
	 CONSTRAINT "CHK_PAYMENT_ORDER_FLAG1" CHECK (PAYMENT_ORDER_FLAG in ('P','G', 'C')) ENABLE, 
	 CHECK (component_type IN ('P', 'F', 'C')) ENABLE, 
	 CHECK (pay_reco_flag IN ('P', 'R')) ENABLE, 
	 CHECK (recovery_from IN ('P', 'G')) ENABLE, 
	 CHECK (tres_breakup_class_type IN ('B', 'C')) ENABLE
   );

COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PAY_RECO_TYPE.PAY_RECO_TYPE_ID IS 'Recovery type id..';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PAY_RECO_TYPE.PAY_RECO_DESC IS 'Recovery type description..';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PAY_RECO_TYPE.PAY_RECO_ABBR IS 'Single word abbreviation for recovery type description..';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PAY_RECO_TYPE.PAY_RECO_FLAG IS 'R for recovery , P --- payment';

CREATE TABLE "IPENSION"."P_MM_PEN_PREP_PENSIONER_DETL" 
   (	"INT_PENSIONER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_GPF_NO_ID_OBS" NUMBER(38,0), 
	"INT_DISTRICT_ID_OBS" NUMBER(38,0), 
	"SUBSCR_FIRST_NAME" VARCHAR2(100), 
	"SUBSCR_MIDDLE_NAME" VARCHAR2(100), 
	"SUBSCR_LAST_NAME" VARCHAR2(100), 
	"INT_REL_ID_OBS" NUMBER(38,0), 
	"DATE_OF_BIRTH" DATE NOT NULL ENABLE, 
	"DATE_OF_EXIT" DATE, 
	"RETIREMENT_DATE" DATE, 
	"EMP_GENDER_OBS" VARCHAR2(1), 
	"INT_MARITAL_STATUS_ID" NUMBER(38,0), 
	"INT_RELIGION_ID" NUMBER(38,0), 
	"INT_NATIONALITY_ID" NUMBER(38,0), 
	"MOBILE_NUMBER" VARCHAR2(11), 
	"EMAIL_ID" VARCHAR2(100), 
	"IDENTIFICATION_MARK" VARCHAR2(400), 
	"INT_IDENTITY_TYPE_ID_OBS" NUMBER(38,0), 
	"IDENTITY_CARD_NUMBER_OBS" VARCHAR2(100), 
	"IFSC_CODE" VARCHAR2(90), 
	"BANK_AC_NO" VARCHAR2(30), 
	"HEIGHT_IN_CENTI" NUMBER(5,2), 
	"INT_PAYABLE_TREA_ID_PEN_OBS" NUMBER(3,0), 
	"INT_DDO_ID" NUMBER(6,0), 
	"CVP_OPTED_FLAG" VARCHAR2(1) DEFAULT 'Y', 
	"CVP_PERCENTAGE" NUMBER(5,2), 
	"P_CITY_VILLAGE_OBS" VARCHAR2(50), 
	"P_TOWN_OBS" VARCHAR2(50), 
	"P_POLICE_STATION_OBS" VARCHAR2(50), 
	"P_DISTRICT_CODE_OBS" VARCHAR2(2), 
	"P_STATE_OBS" NUMBER(2,0), 
	"P_PIN_OBS" VARCHAR2(50), 
	"C_CITY_VILLAGE_OBS" VARCHAR2(50), 
	"C_TOWN_OBS" VARCHAR2(50), 
	"C_POLICE_STATION_OBS" VARCHAR2(50), 
	"C_DISTRICT_CODE_OBS" VARCHAR2(2), 
	"C_STATE_OBS" NUMBER(2,0), 
	"C_PIN_OBS" VARCHAR2(50), 
	"PEN_FILE_ID" NUMBER(38,0), 
	"LAST_POST_ID_OBS" NUMBER(38,0), 
	"INSTITUTE_ID_OBS" NUMBER(38,0), 
	"SEND_TO_USER_ID_OBS" NUMBER(8,0), 
	"ACTIVE_FLAG" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"PROCESSING_FLAG" NUMBER(2,0) NOT NULL ENABLE, 
	"PREV_INT_PENSIONER_ID" NUMBER(38,0), 
	"IDENTIFICATION_MARK2" VARCHAR2(400), 
	"PAN_NO" VARCHAR2(10), 
	"FINAL_GPF_APPLIED_FLAG" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"FINAL_GPF_APPLIED_DATE" DATE, 
	"REASON_FINAL_GPF_NOT_APPLY" VARCHAR2(400), 
	"PREVIOUS_PENSION_TYPE" CHAR(1), 
	"PREVIOUS_PENSION_SOURCE" CHAR(1), 
	"PREVIOUS_PENSION_PPO_NO" VARCHAR2(30), 
	"PREVIOUS_PENSION_AMT" NUMBER(14,2), 
	"PREVIOUS_PENSION_WEF" DATE, 
	"FINAL_GPF_APPLIED_LETTER_NO" VARCHAR2(30), 
	"BSR_CODE" VARCHAR2(30), 
	"HRMS_EMP_ID_OBS" VARCHAR2(30), 
	"DECLRN_CHECK_FLAG" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"DML_STATUS_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"PREV_INT_TREASURY_ID" NUMBER(3,0), 
	"PREV_BANK_IFSC_CODE" VARCHAR2(90), 
	"PREV_PIA" VARCHAR2(100), 
	"EDU_QUALIFICATION_OBS" VARCHAR2(200), 
	"TRAINING_OBS" VARCHAR2(400), 
	"PEN_TYPE_ID" NUMBER(38,0), 
	"SALUTATION_NAME_OF_RELATIVE_OB" VARCHAR2(50), 
	"FIRST_NAME_OF_RELATIVE_OBS" VARCHAR2(50), 
	"MIDDLE_NAME_OF_RELATIVE_OBS" VARCHAR2(50), 
	"LAST_NAME_OF_RELATIVE_OBS" VARCHAR2(50), 
	"INT_DESIGNATION_ID" NUMBER(38,0), 
	"INT_POST_ID" NUMBER(38,0), 
	"PENSION_FILE_NO" VARCHAR2(100), 
	"DESIGNATION_DESC" VARCHAR2(500), 
	"POST_DESC" VARCHAR2(500), 
	"INT_CADRE_ID" NUMBER(38,0), 
	"CADRE_DESC" VARCHAR2(500), 
	"INT_SRV_ID" NUMBER(38,0), 
	"SERVICE_TYPE_DESC" VARCHAR2(500), 
	"INT_EMPLOYMENT_TYPE" NUMBER(38,0), 
	"EMPLOYMENT_TYPE_DESC" VARCHAR2(500), 
	"TREASURY_CODE_PAYABLE" VARCHAR2(4), 
	"INT_EMPLOYEE_ID" NUMBER(38,0), 
	"EMPLOYEE_NO" VARCHAR2(50), 
	"REQUEST_ID" NUMBER(15,0), 
	"TRES_CODE_PAYABLE_OUT_STATE" VARCHAR2(500), 
	"WB_HEALTH_SCHEME_FLAG" VARCHAR2(1), 
	"HEALTH_SCHEME_TO_BE_CONTINUED" VARCHAR2(1), 
	"MEMBER_OF_GPF" VARCHAR2(1), 
	"GPF_SERIES" VARCHAR2(30), 
	"GPF_SERIES1" VARCHAR2(12), 
	"GPF_ACCOUNT_NO" VARCHAR2(20), 
	"INT_HEAD_OF_OFFICE_ID" NUMBER(38,0), 
	"INT_APP_AUTHORITY_ID" NUMBER(38,0), 
	"FROM_ESS" VARCHAR2(1), 
	"INT_PREP_DECLARATION_ID" NUMBER(38,0), 
	"BANK_OBS" VARCHAR2(300), 
	"BRANCH_NAME_OBS" VARCHAR2(2000), 
	"BENF_TYPE_ID" NUMBER(38,0), 
	"EMP_INT_OMI_GENDER" NUMBER(38,0), 
	"MARITAL_STATUS_DESC" VARCHAR2(300), 
	"RELIGION_DESC" VARCHAR2(300), 
	"GENDER_DESC" VARCHAR2(30), 
	"INT_PAYABLE_TREA_ID_GRAT_OBS" NUMBER(3,0), 
	"SALUTATION_NAME_OF_EMPL_OBS" VARCHAR2(50), 
	"PAYABLE_TREASURY_FLAG" VARCHAR2(1), 
	"PAYABLE_OUT_TREASURY_NAME" VARCHAR2(50), 
	"ROLE_ID" NUMBER(6,0), 
	"MODIFIED_ROLE_ID" NUMBER(6,0), 
	"APPLICATION_DATE" DATE, 
	"RETIREMENT_FORE_AFT_NOON" NUMBER(1,0) DEFAULT 1, 
	"NATIONALITY" VARCHAR2(50), 
	"INT_DEPT_ID" NUMBER(10,0), 
	"DEPT_DESCRIPTION" VARCHAR2(100), 
	"INT_SANCTIONING_AUTHORITY_ID" NUMBER(38,0), 
	"SANCTIONING_AUTHORITY_TYPE" VARCHAR2(10), 
	"APPOINTMENT_ADD_HOC_FLAG" VARCHAR2(1), 
	"PREVIOUS_CVP_APPLICATION_FLAG" VARCHAR2(1), 
	"PREVIOUS_CVP_APPLI_REMARKS" VARCHAR2(500), 
	"PREV_APPEARANCE_MEDICAL_FLAG" VARCHAR2(1), 
	"PREV_APPEAR_MEDICAL_REMARKS" VARCHAR2(500), 
	"PPO_NUMBER" VARCHAR2(30), 
	"INT_POST_CODE" NUMBER(38,0), 
	"POST_CODE" VARCHAR2(50), 
	"FORWARDING_AUTHORITY_OBS" VARCHAR2(6), 
	"INT_SERVICE_BOOK_AVAIL" NUMBER(38,0), 
	"COURT_CASE_PENDING_STATUS" VARCHAR2(1), 
	"COURT_CASE_REMARKS" VARCHAR2(500), 
	"APPROVER_USER_ID" NUMBER(8,0), 
	"APPROVER_ROLE_ID" NUMBER(6,0), 
	"APPROVE_TIME_STAMP" TIMESTAMP (6), 
	"DATE_OF_JOINING" DATE, 
	"PEN_SANCTION_INT_TREASURY_ID" NUMBER(3,0), 
	"INT_OMI_PF_NPS_TYPE" NUMBER(38,0), 
	"PSA_CODE" VARCHAR2(40), 
	"RE_EMPLOYED_AFT_RETIR_REMARKS" VARCHAR2(500), 
	"FAMILY_PENSIONER_EMPLOYED_FLAG" VARCHAR2(1), 
	"FAMILY_PEN_EMPLOYED_REMARKS" VARCHAR2(500), 
	"FAMILY_PEN_RCPT_PEN_REMARKS" VARCHAR2(500), 
	"CPF_SHARE_REMARKS" VARCHAR2(1000), 
	"PROVISIONAL_PENSION_REMARKS" VARCHAR2(500), 
	"PROVISIONAL_GRATUITY_REMARKS" VARCHAR2(500), 
	"APPOINTMENT_ADD_HOC_REMARKS" VARCHAR2(500), 
	"OTHER_PENSION_RECEIPT_FLAG" VARCHAR2(1), 
	"OTHER_PENSION_RCPT_NAME" VARCHAR2(500), 
	"OTHER_PENSION_RCPT_PARTICULAR" VARCHAR2(500), 
	"OTHER_PENSION_RCPT_SOURCE" VARCHAR2(500), 
	"VIGILANCE_CASE_PENDING_REMARKS" VARCHAR2(500), 
	"DEPT_CRIMINAL_PROC_REMARKS" VARCHAR2(500), 
	"RE_EMPLOYED_AFTER_RETIRE_FLAG" VARCHAR2(1), 
	"FAMILY_PEN_RCPT_OTH_PEN_FLAG" VARCHAR2(1), 
	"PROVISIONAL_PEN_RECEIVED_FLAG" VARCHAR2(1), 
	"PROVISIONAL_GRATUITY_RCVD_FLAG" VARCHAR2(1), 
	"VIGILANCE_CASE_PENDING_FLAG" VARCHAR2(1), 
	"DEPT_CRIMINAL_PROC_PENDING_FLG" VARCHAR2(1), 
	"TRES_NAME_PAYABLE_OUT_STATE" VARCHAR2(500), 
	"TRES_CODE_PAYABLE_OUT_STATE_ID" NUMBER(38,0), 
	"PSA_TREASURY_MODIFIABLE_FLAG" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"INT_PSA_TREASURY_CODE" VARCHAR2(5), 
	"INT_HEAD_OF_OFFICE_ID_SB" NUMBER(38,0), 
	"PSA_DDO_AVL_FLAG" VARCHAR2(1) DEFAULT 'N', 
	"OTHER_PPO_NO" VARCHAR2(30), 
	"OTHER_PPO_DETAILS" VARCHAR2(500), 
	"WRIT_PETITION_NO" VARCHAR2(30), 
	"WRIT_PETITION_DETAILS" VARCHAR2(500), 
	"PROCESSING_STAGE_DTL" VARCHAR2(4), 
	"INT_OMI_COURT_CASE_TYPE" NUMBER(38,0), 
	"COURT_CASE_TYPE" VARCHAR2(100), 
	"COURT_CASE_NO" VARCHAR2(100), 
	"COURT_CASE_YEAR" NUMBER(4,0), 
	"NAME_OF_COURT" VARCHAR2(200), 
	"INT_OMI_CASE_STATUS" NUMBER(38,0), 
	"INT_OMI_CASE_RELATION_TO" NUMBER(38,0), 
	"CASE_REL_OTHER_REASON" VARCHAR2(1000), 
	"NAME_OF_THE_AUTHORITY" VARCHAR2(200), 
	"REMARKS" VARCHAR2(500), 
	"PENSION_TYPE_FLAG" VARCHAR2(1), 
	"PENSION_CALC_TYPE" VARCHAR2(2), 
	"INT_PSA_DDO_ID" NUMBER(7,0), 
	"PROV_PEN_SYSTEM_RCVD_FLAG" VARCHAR2(1) DEFAULT 'N', 
	"PROV_GRAT_SYSTEM_RCVD_FLAG" VARCHAR2(1) DEFAULT 'N', 
	"RATE_OF_PROV_PENSION" NUMBER(7,0), 
	"PROV_PENSION_PERIOD" VARCHAR2(100), 
	"RATE_OF_PROV_GRATUITY" NUMBER(7,0), 
	"GRATUITY_PAYMENT_ORDER_NO" VARCHAR2(100), 
	"COMMUTED_VALUE_PAY_ORDER_NO" VARCHAR2(100), 
	"APPROVAL_AUTH_DESIGNATION" VARCHAR2(300), 
	"INT_SPOUSE_RELIGION_ID" NUMBER(38,0), 
	"INT_PSA_DESIGNATION_ID" NUMBER(38,0), 
	"PSA_ADDRESS" VARCHAR2(1000), 
	"TREASURY_BANK" VARCHAR2(100), 
	"TREASURY_NAME" VARCHAR2(100), 
	 CONSTRAINT "PK_P_MM_PEN_PREP_PEN_DETL" PRIMARY KEY ("INT_PENSIONER_ID") ENABLE, 
	 CONSTRAINT "UK_P_MM_PEN_PREP_PEN_DETL1" UNIQUE ("PEN_FILE_ID") ENABLE, 
	 CONSTRAINT "UK_P_MM_PEN_PREP_PEN_DETL2" UNIQUE ("PENSION_FILE_NO") DISABLE, 
	 CONSTRAINT "CHK_P_MM_PEN_PREP_PENS_DETL1" CHECK (EMP_GENDER_obs in('M','F')) ENABLE, 
	 CONSTRAINT "CHK_P_MM_PEN_PREP_PENS_DETL10" CHECK (FAMILY_PEN_RCPT_OTH_PEN_FLAG in ('Y','N')) ENABLE, 
	 CONSTRAINT "CHK_P_MM_PEN_PREP_PENS_DETL11" CHECK (PROVISIONAL_PEN_RECEIVED_FLAG in  ('Y','N')) ENABLE, 
	 CONSTRAINT "CHK_P_MM_PEN_PREP_PENS_DETL12" CHECK (PROVISIONAL_GRATUITY_RCVD_FLAG in  ('Y','N')) ENABLE, 
	 CONSTRAINT "CHK_P_MM_PEN_PREP_PENS_DETL13" CHECK (OTHER_PENSION_RECEIPT_flag in  ('Y','N')) ENABLE, 
	 CONSTRAINT "CHK_P_MM_PEN_PREP_PENS_DETL14" CHECK (VIGILANCE_CASE_PENDING_FLAG in  ('Y','N')) ENABLE, 
	 CONSTRAINT "CHK_P_MM_PEN_PREP_PENS_DETL15" CHECK (DEPT_CRIMINAL_PROC_PENDING_FLG  in  ('Y','N')) ENABLE, 
	 CONSTRAINT "CHK_P_MM_PEN_PREP_PENS_DETL2" CHECK (FINAL_GPF_APPLIED_FLAG IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "CHK_P_MM_PEN_PREP_PENS_DETL4" CHECK (PREVIOUS_PENSION_TYPE IN ('N', 'F')) ENABLE, 
	 CONSTRAINT "CHK_P_MM_PEN_PREP_PENS_DETL5" CHECK (PREVIOUS_PENSION_SOURCE IN  ('M', 'C', 'O')) ENABLE, 
	 CONSTRAINT "CHK_P_MM_PEN_PREP_PENS_DETL7" CHECK (COURT_CASE_PENDING_STATUS in ('Y','N')) ENABLE, 
	 CONSTRAINT "CHK_P_MM_PEN_PREP_PENS_DETL8" CHECK (RE_EMPLOYED_AFTER_RETIRE_FLAG in  ('Y','N')) ENABLE, 
	 CONSTRAINT "CHK_P_MM_PEN_PREP_PENS_DETL9" CHECK (FAMILY_PENSIONER_EMPLOYED_FLAG in ('Y','N')) ENABLE
   );

COMMENT ON TABLE IPENSION.P_MM_PEN_PREP_PENSIONER_DETL IS 'Store Pensioner Personal information';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.INT_PENSIONER_ID IS 'pensioner id which is unique';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.INT_GPF_NO_ID_OBS IS 'gpf-tpf number id referencing column from PF_MM_GEN_SUBSCR_DETL';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.INT_DISTRICT_ID_OBS IS 'District id of pensioner';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.RETIREMENT_DATE IS 'to be fetched from employee master table -- added by ritu';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.INT_MARITAL_STATUS_ID IS 'referencing from PF_MM_GEN_MARITAL_STATUS table indication maritial states.';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.BANK_AC_NO IS 'bank account id..';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.PEN_FILE_ID IS 'unique for every pensioner';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.LAST_POST_ID_OBS IS 'Last post dat the pensioner hold referencing from P_MM_PEN_PREP_POST';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.INSTITUTE_ID_OBS IS 'unique id of the institute..';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.FINAL_GPF_APPLIED_FLAG IS 'Y - Yes, N - No';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.PREVIOUS_PENSION_TYPE IS 'N for Normal, F for Family';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.PREVIOUS_PENSION_SOURCE IS 'M - Military, C - Civil, O - Others';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.PEN_TYPE_ID IS 'Unique pension ID type.';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.BENF_TYPE_ID IS 'no use of this';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.PAYABLE_TREASURY_FLAG IS 'B: Bank, I-Treasury, O: outside WB(State ) ';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.PAYABLE_OUT_TREASURY_NAME IS 'For PAYABLE_TREASURY_FLAG ''I'' Traeasury name ''O'' State name';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.RETIREMENT_FORE_AFT_NOON IS '0 for forenoon and 1 for afternoon';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.SANCTIONING_AUTHORITY_TYPE IS 'AA --------- Appointing Auth, HOO----------- Head Of Office';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.COURT_CASE_PENDING_STATUS IS 'Y/N';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.COURT_CASE_REMARKS IS 'For Departmental Proceedings & ''Judicial'' Proceedings.';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.CPF_SHARE_REMARKS IS '19';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.OTHER_PENSION_RECEIPT_FLAG IS '22/f';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.RE_EMPLOYED_AFTER_RETIRE_FLAG IS 'Y/N';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.PROVISIONAL_PEN_RECEIVED_FLAG IS '35/a';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.PROVISIONAL_GRATUITY_RCVD_FLAG IS '35/b';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.INT_PSA_TREASURY_CODE IS 'treasury attached with DDO of Service Book HOO';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.INT_HEAD_OF_OFFICE_ID_SB IS 'SERVICE BOOK HOO';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.PSA_DDO_AVL_FLAG IS 'SERVICE BOOK HOO tagged with DDO or Not';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.OTHER_PPO_NO IS 'If family pensioner received any other pension or family pension then that PPO Number to be provided';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.OTHER_PPO_DETAILS IS 'If family pensioner received any other pension or family pension then that PPO Details to be provided';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.WRIT_PETITION_NO IS 'If court case pending is Yes Then W.P(Writ Petition) No to be provided';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.WRIT_PETITION_DETAILS IS 'If court case pending is Yes Then W.P(Writ Petition) Details to be provided';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.PROCESSING_STAGE_DTL IS 'For Detail Of Processing Status';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.INT_OMI_COURT_CASE_TYPE IS 'Case Type: ''Judicial Proceedings'', �Departmental Proceedings� Taken from OtherMaster Master Type'' CCT''';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.COURT_CASE_TYPE IS 'For Judicial Proceedings Only';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.COURT_CASE_NO IS 'For Judicial Proceedings Only';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.COURT_CASE_YEAR IS 'For Judicial Proceedings Only';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.NAME_OF_COURT IS 'For Judicial Proceedings Only';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.INT_OMI_CASE_STATUS IS 'For Departmental Proceedings & ''Judicial'' Proceedings.';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.INT_OMI_CASE_RELATION_TO IS 'For Judicial Proceedings Only';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.CASE_REL_OTHER_REASON IS 'For Judicial Proceedings Only';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.NAME_OF_THE_AUTHORITY IS 'For Departmental Proceedings Only';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.REMARKS IS 'Remarks For General Purpose';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.PENSION_TYPE_FLAG IS '''F'' for Final ''P'' for Provisional';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.PENSION_CALC_TYPE IS 'Types are commomn Superannuation & ''Death'' ''SP'' & ''DP''';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.INT_PSA_DDO_ID IS 'Tagged DDO of Service Book HOO';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.PROV_PEN_SYSTEM_RCVD_FLAG IS 'If Provisional Pension is system calculated then ''Y'' Else ''N''';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.PROV_GRAT_SYSTEM_RCVD_FLAG IS 'If Provisional Gratuity is system calculated then ''Y'' Else ''N''';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.RATE_OF_PROV_PENSION IS 'as per CR 181305 Point 1';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.PROV_PENSION_PERIOD IS 'as per CR 181305 Point 1';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.RATE_OF_PROV_GRATUITY IS 'as per CR 181305 Point 1';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.GRATUITY_PAYMENT_ORDER_NO IS 'as per CR 181305 Point 2';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.COMMUTED_VALUE_PAY_ORDER_NO IS 'as per CR 181305 Point 2';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.APPROVAL_AUTH_DESIGNATION IS 'as per CR 208818 Point 1';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.INT_SPOUSE_RELIGION_ID IS 'as per CR 275470';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.TREASURY_BANK IS 'as per CR 480156';
COMMENT ON COLUMN IPENSION.P_MM_PEN_PREP_PENSIONER_DETL.TREASURY_NAME IS 'as per CR 480156';

CREATE TABLE "IPENSION"."P_MM_PEN_PROCESSING_FLAG" 
   (	"PROCESSING_FLAG" NUMBER(2,0) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(100) NOT NULL ENABLE, 
	"ACTIVE_FLAG" VARCHAR2(1) DEFAULT 'Y', 
	"USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_P_MM_PEN_PROCESSING_FLAG" PRIMARY KEY ("PROCESSING_FLAG") ENABLE
   );
;

CREATE TABLE "IPENSION"."P_MM_PEN_RETIREMENT_BENF_TYPE" 
   (	"BENF_TYPE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"BENF_DESC" VARCHAR2(300) NOT NULL ENABLE, 
	"BENF_ABBR" VARCHAR2(4) NOT NULL ENABLE, 
	"ACTIVE_FLAG" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	"NOMINEE_FLAG" VARCHAR2(1), 
	 CONSTRAINT "PK_P_MM_PEN_RETIRE_BENF_TYPE" PRIMARY KEY ("BENF_TYPE_ID") ENABLE
   );

COMMENT ON COLUMN IPENSION.P_MM_PEN_RETIREMENT_BENF_TYPE.NOMINEE_FLAG IS 'For selecting nominee, value should be ''Y''-- added by ritu';

CREATE TABLE "IPENSION"."P_MM_PEN_RULE_DTLS" 
   (	"INT_PEN_RULE_DTLS_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PEN_RULE_NAME_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PAY_RECO_TYPE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"RULE_NAME" VARCHAR2(300), 
	"RULE_ABBR" VARCHAR2(10), 
	"RULES_REMARKS" VARCHAR2(500), 
	"MIN_SERVICE_YR" NUMBER(12,1), 
	"MIN_SERVICE_YR_OPERATOR" VARCHAR2(10), 
	"MAX_SERVICE_YR" NUMBER(12,1), 
	"MAX_SERVICE_YR_OPERATOT" VARCHAR2(10), 
	"PERCENT_OF_AMT" NUMBER(12,0), 
	"MAX_SERVICE_YEAR" NUMBER(12,0), 
	"RETIREMENT_DATE_FROM" DATE, 
	"RETIREMENT_DATE_TO" DATE, 
	"MIN_CALCULATED_AMT" NUMBER(10,0), 
	"MAX_CALCULATED_AMT" NUMBER(10,0), 
	"RULES" VARCHAR2(999), 
	"ACTIVE_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"ROPA_ABBR" VARCHAR2(50), 
	 CONSTRAINT "PK_P_MM_PEN_RULE_DTLS" PRIMARY KEY ("INT_PEN_RULE_DTLS_ID") ENABLE
   );

COMMENT ON COLUMN IPENSION.P_MM_PEN_RULE_DTLS.ROPA_ABBR IS 'pay_allowance_abbr';

CREATE TABLE "IPENSION"."P_MM_PEN_RULE_NAME" 
   (	"INT_PEN_RULE_NAME_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_SERVICE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"RULE_NAME" VARCHAR2(300) NOT NULL ENABLE, 
	"RULE_ABBR" VARCHAR2(10) NOT NULL ENABLE, 
	"BENF_TYPE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PEN_TYPE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"WEF" DATE NOT NULL ENABLE, 
	"ACTIVE_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"DML_STATUS_FLAG" NUMBER(1,0) NOT NULL ENABLE, 
	"CREATED_USER_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"CREATED_TIME_STAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"CREATED_ROLE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0), 
	"MODIFIED_TIME_STAMP" TIMESTAMP (6) DEFAULT systimestamp, 
	"MODIFIED_ROLE_ID" NUMBER(6,0), 
	 CONSTRAINT "PK_P_MM_PEN_RULE_NAME" PRIMARY KEY ("INT_PEN_RULE_NAME_ID") ENABLE, 
	 CONSTRAINT "UK_P_MM_PEN_RULE_NAME1" UNIQUE ("RULE_NAME") ENABLE, 
	 CONSTRAINT "UK_P_MM_PEN_RULE_NAME2" UNIQUE ("RULE_ABBR") ENABLE
   );
;

CREATE TABLE "IPENSION"."P_MM_PEN_RULE_SUB_DTLS" 
   (	"INT_PEN_RULE_SUB_DTLS_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PEN_RULE_DTLS_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"MIN_BASIC_PAY" NUMBER(10,0), 
	"MAX_BASIC_PAY" NUMBER(10,0), 
	"PERCENT_BASIC_PAY" NUMBER(10,0), 
	"MIN_CALCULATED_AMT" NUMBER(10,0), 
	"MAX_CALCULATED_AMT" NUMBER(10,0), 
	"RULES" VARCHAR2(999), 
	 CONSTRAINT "UK_P_MM_PEN_RULE_SUB_DTLS" PRIMARY KEY ("INT_PEN_RULE_SUB_DTLS_ID") ENABLE
   );
;

CREATE TABLE "IPENSION"."P_TD_PEN_PREP_ATTACHEMENT_DTL" 
   (	"INT_ATTACHEMENT_DTL_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"DOCUMENT_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"CONTENT_ID" VARCHAR2(38) NOT NULL ENABLE, 
	"INT_EMPLOYEE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ACTIVE_FLAG" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"DML_STATUS_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp, 
	"ROLE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"MODIFIED_ROLE_ID" NUMBER(6,0), 
	"REQUEST_ID" NUMBER(15,0), 
	"INT_PEN_PREP_ATTACHEMENT" NUMBER(38,0), 
	"REQUEST_TYPE" VARCHAR2(15), 
	"FILE_NAME" VARCHAR2(100), 
	"FILE_TYPE" VARCHAR2(20), 
	 CONSTRAINT "PK_P_TD_PEN_PREP_ATTACH_DTL" PRIMARY KEY ("INT_ATTACHEMENT_DTL_ID") ENABLE, 
	 CONSTRAINT "UK_P_TD_PEN_PREP_ATTACH_DTL1" UNIQUE ("DOCUMENT_ID") ENABLE, 
	 CONSTRAINT "UK_P_TD_PEN_PREP_ATTACH_DTL2" UNIQUE ("CONTENT_ID") ENABLE
   );
;

CREATE TABLE "IPENSION"."P_TD_PEN_PREP_ATTACHMENT_DTL" 
   (	"INT_ATTACHEMENT_DTL_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"DOCUMENT_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"CONTENT_ID" VARCHAR2(38) NOT NULL ENABLE, 
	"INT_EMPLOYEE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ACTIVE_FLAG" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"DML_STATUS_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp, 
	"ROLE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"MODIFIED_ROLE_ID" NUMBER(6,0), 
	"REQUEST_ID" NUMBER(15,0), 
	"INT_PEN_PREP_ATTACHEMENT" NUMBER(38,0), 
	"REQUEST_TYPE" VARCHAR2(15), 
	"FILE_NAME" VARCHAR2(100), 
	"FILE_TYPE" VARCHAR2(20), 
	"INT_PENSIONER_ID" NUMBER(38,0), 
	"INT_OMI_UPD_DOC_TYPE" NUMBER(38,0)
   );

COMMENT ON COLUMN IPENSION.P_TD_PEN_PREP_ATTACHMENT_DTL.INT_OMI_UPD_DOC_TYPE IS 'document type from other master master type: ''AFT''';

CREATE TABLE "IPENSION"."P_TD_PEN_PREP_FAMILY_ADDRESS" 
   (	"INT_FAMILY_ADDR_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PENSIONER_ID" NUMBER(38,0), 
	"FAMILY_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"HOUSE_NO_STREET_LANE" VARCHAR2(100), 
	"CITY_TOWN_VILLAGE" VARCHAR2(100), 
	"POST_OFFICE" VARCHAR2(100), 
	"POLICE_STATION" VARCHAR2(100), 
	"STATE_ID" NUMBER(2,0), 
	"INT_DISTRICT_ID" NUMBER(5,0), 
	"PIN" VARCHAR2(10), 
	"WEF" TIMESTAMP (6), 
	"ADDR_TYPE" VARCHAR2(5), 
	"SAME_AS_PERMANENT_ADDR" VARCHAR2(5) DEFAULT 'N', 
	"ACTIVE_FLAG" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CREATED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CREATED_ROLE_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"MODIFIED_ROLE_ID" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE, 
	"EFFECTIVE_END_DATE" DATE, 
	"DML_STATUS_FLAG" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER(15,0), 
	"INT_RELATION_ADDR_ID" NUMBER(38,0), 
	 CONSTRAINT "PK_P_TD_PEN_PREP_FAMILY_ADDR" PRIMARY KEY ("INT_FAMILY_ADDR_ID") ENABLE
   );
;

CREATE TABLE "IPENSION"."P_TD_PEN_PREP_FAMILY_DTL" 
   (	"PEN_FILE_ID_OBS" NUMBER(38,0), 
	"FAMILY_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"REL_FIRST_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"INT_REL_ID_OBS" NUMBER(38,0), 
	"GENDER_OBS" CHAR(1), 
	"DOB" DATE, 
	"INT_MARITAL_STATUS_ID" NUMBER(38,0), 
	"EFP_UPTO" DATE, 
	"SHARE_PERCENTAGE_OBS" NUMBER(3,0), 
	"HANDICAPP_FLAG_OBS" CHAR(1), 
	"MINOR_FLAG_OBS" CHAR(1), 
	"MINOR_FLAG_CALCULATED_ON_OBS" DATE DEFAULT SYSDATE, 
	"BANK_AC_NO_OBS" VARCHAR2(30), 
	"IFSC_CODE_OBS" VARCHAR2(11), 
	"HANDICAPP_TYPE_OBS" CHAR(1), 
	"REMARKS" VARCHAR2(200), 
	"GUARDIAN_NAME_OBS" VARCHAR2(200), 
	"MOBILE_NUMBER" VARCHAR2(11), 
	"DML_STATUS_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	"SALUTATION_FAMILY_OBS" VARCHAR2(50), 
	"SALUTATION_FAMILY_GUARDIAN_OBS" VARCHAR2(50), 
	"TI_APPLICABLE_FLAG_OBS" CHAR(1), 
	"INT_PENSIONER_ID" NUMBER(38,0), 
	"INT_EMP_RELATIONSHIP_ID" NUMBER(38,0), 
	"REL_INT_OMI_RELATIONSHIP" NUMBER(38,0), 
	"ACTIVE_FLAG" VARCHAR2(1), 
	"REL_INT_OMI_PHYSIC_CHALLENGED" NUMBER(38,0), 
	"REL_PHYSIC_CHALLENGED_PERC_VH" NUMBER(3,0), 
	"REL_PHYSIC_CHALLENGED_PERC_PH" NUMBER(3,0), 
	"REQUEST_ID" NUMBER(15,0), 
	"WBHS_CARD_NUMBER" VARCHAR2(50), 
	"HEALTH_INSURANCE_TYPE" VARCHAR2(1), 
	"RELATIONSHIP_EMP_NO" VARCHAR2(50), 
	"INT_EMPLOYEE_ID" NUMBER(38,0), 
	"CREATED_ROLE_ID" NUMBER(6,0), 
	"MODIFIED_ROLE_ID" NUMBER(6,0), 
	"DECEASED_FLAG" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"FAMILY_PENSION_FLAG" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"MARRIAGE_DATE" DATE, 
	"REL_EXACT_HEIGHT" NUMBER(7,2), 
	"INT_REL_OMI_HEIGHT_UNIT" NUMBER(38,0), 
	"REL_IDENTIFICATION_MARK" VARCHAR2(200), 
	 CONSTRAINT "PK_P_TD_PEN_PREP_FAMILY_DTL" PRIMARY KEY ("FAMILY_ID") ENABLE, 
	 CONSTRAINT "CHK_TI_APPLICABLE_FLAG" CHECK (TI_APPLICABLE_FLAG_obs in ('Y', 'N')) ENABLE, 
	 CHECK (HANDICAPP_FLAG_obs IN ('Y','N')) ENABLE, 
	 CHECK (GENDER_obs IN ('M','F')) ENABLE, 
	 CHECK (MINOR_FLAG_obs IN ('Y','N')) ENABLE
   );

COMMENT ON COLUMN IPENSION.P_TD_PEN_PREP_FAMILY_DTL.PEN_FILE_ID_OBS IS 'unique pension id for the pensioner..';
COMMENT ON COLUMN IPENSION.P_TD_PEN_PREP_FAMILY_DTL.FAMILY_ID IS 'unique family id..';
COMMENT ON COLUMN IPENSION.P_TD_PEN_PREP_FAMILY_DTL.REL_FIRST_NAME IS 'name of the family member';
COMMENT ON COLUMN IPENSION.P_TD_PEN_PREP_FAMILY_DTL.INT_REL_ID_OBS IS 'relationshp of pensioner with this member..';
COMMENT ON COLUMN IPENSION.P_TD_PEN_PREP_FAMILY_DTL.GENDER_OBS IS 'gender of the pensioner..';
COMMENT ON COLUMN IPENSION.P_TD_PEN_PREP_FAMILY_DTL.DOB IS 'date of birth of pensioner..';
COMMENT ON COLUMN IPENSION.P_TD_PEN_PREP_FAMILY_DTL.INT_MARITAL_STATUS_ID IS 'mariatial status of the relationship of pensionar';
COMMENT ON COLUMN IPENSION.P_TD_PEN_PREP_FAMILY_DTL.EFP_UPTO IS 'EFP up to date..';
COMMENT ON COLUMN IPENSION.P_TD_PEN_PREP_FAMILY_DTL.SHARE_PERCENTAGE_OBS IS 'Share percentage of the family member..';
COMMENT ON COLUMN IPENSION.P_TD_PEN_PREP_FAMILY_DTL.HANDICAPP_FLAG_OBS IS 'Whether this member is handicapped..';
COMMENT ON COLUMN IPENSION.P_TD_PEN_PREP_FAMILY_DTL.MINOR_FLAG_OBS IS 'whether this member is minor..';
COMMENT ON COLUMN IPENSION.P_TD_PEN_PREP_FAMILY_DTL.BANK_AC_NO_OBS IS 'bank account id..';
COMMENT ON COLUMN IPENSION.P_TD_PEN_PREP_FAMILY_DTL.HANDICAPP_TYPE_OBS IS '''P'' for Physically Handicapped and ''M'' for Mentally Handicapped';
COMMENT ON COLUMN IPENSION.P_TD_PEN_PREP_FAMILY_DTL.INT_PENSIONER_ID IS 'pensioner id which is unique';
COMMENT ON COLUMN IPENSION.P_TD_PEN_PREP_FAMILY_DTL.REL_INT_OMI_RELATIONSHIP IS 'RL type in other master';
COMMENT ON COLUMN IPENSION.P_TD_PEN_PREP_FAMILY_DTL.REL_INT_OMI_PHYSIC_CHALLENGED IS 'PHC in Otehr Master';
COMMENT ON COLUMN IPENSION.P_TD_PEN_PREP_FAMILY_DTL.DECEASED_FLAG IS '''Y'' for alive ''N'' for dead';
COMMENT ON COLUMN IPENSION.P_TD_PEN_PREP_FAMILY_DTL.FAMILY_PENSION_FLAG IS '''Y'' for family pension admisible else ''N''';
COMMENT ON COLUMN IPENSION.P_TD_PEN_PREP_FAMILY_DTL.MARRIAGE_DATE IS 'Added for Requirement of Exit Management';

CREATE TABLE "IPENSION"."P_TD_PEN_PREP_FAMILY_PEN_DTL" 
   (	"INT_PREP_FAMILY_PEN_DTL" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PENSIONER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"FAMILY_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"REMARKS" VARCHAR2(300), 
	"DML_STATUS_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	"MODIFIED_USER_ID" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"CREATED_ROLE_ID" NUMBER(6,0), 
	"MODIFIED_ROLE_ID" NUMBER(6,0), 
	"ACTIVE_FLAG" VARCHAR2(1), 
	"INT_NOM_ID" NUMBER(38,0), 
	 CONSTRAINT "PK_P_TD_PEN_PREP_FAM_PEN_DTL" PRIMARY KEY ("INT_PREP_FAMILY_PEN_DTL") ENABLE
   );
;

CREATE TABLE "IPENSION"."P_TD_PEN_PREP_FILE_PROCESS_LOG" 
   (	"PEN_FILE_PROCESS_LOG_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"INT_PENSIONER_ID" NUMBER(38,0), 
	"PEN_FILE_PROCESS_SEQ" NUMBER(38,0) NOT NULL ENABLE, 
	"PROCESSING_FLAG" NUMBER(2,0) NOT NULL ENABLE, 
	"PROCESS_BY" NUMBER(6,0) NOT NULL ENABLE, 
	"PROCESS_DATE" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	"DML_STATUS_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"PROCESSED_BY_USER_TYPE" VARCHAR2(2), 
	"SUB_SYSTEM_ID" NUMBER(3,0) NOT NULL ENABLE, 
	"PROCESSED_BY_USER_ROLE_ID" NUMBER(3,0), 
	"REMARKS" VARCHAR2(300), 
	"SEND_TO_USER_ID" NUMBER(8,0), 
	"SEND_TO_USER_TYPE" VARCHAR2(2), 
	"SEND_TO_USER_ROLE_ID" NUMBER(3,0), 
	"PROCESSED_BY_AUTH_ID" NUMBER(38,0), 
	"SEND_TO_AUTH_ID" NUMBER(38,0), 
	 CONSTRAINT "PK_P_TD_PEN_PREP_FILE_PROC_LOG" PRIMARY KEY ("PEN_FILE_PROCESS_LOG_ID") ENABLE, 
	 CONSTRAINT "UK_P_TD_PEN_PREP_FILE_PRO_LOG1" UNIQUE ("PEN_FILE_PROCESS_LOG_ID", "PEN_FILE_PROCESS_SEQ") ENABLE, 
	 CONSTRAINT "CHK_P_TD_PENPR_FILE_LOG" CHECK (PROCESSING_FLAG in (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,-2,-3,-6,-12,-13,99)) ENABLE
   );
;